# RPGMenu plugin.yml - See https://bukkit.gamepedia.com/Plugin_YAML/de for more information
name: RPGMenu
version: 2.0
description: 'A addon for BetonQuest which allows you to simply create your own guis by using events and items from BetonQuest.'
author: ungefroren
website: https://github.com/joblo2213/RPGMenu
main: de.ungefroren.rpgmenu.RPGMenu
depend: [BetonQuest]
